# Site settings
title: Boonil Bej

keywords: art
description: Emerging artist.

# Only use this if you are serving your site via Github Pages
github:
  url: "boonil.com/"

header: images/logo.png

# Exclude our ruby stuff
exclude: [.bundle, .vendor, .bin, starving-artist.gemspec, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, starving-artist-jekyll-theme-*.gem]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

theme: starving-artist-jekyll-theme

include: ['_pages']

permalink: /updates/:year/:title

collections:
  - galleries

#### SEO Stuff
# Google Analytics
google_universal_analytics:
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
facebook_user:
facebook_app_id:                                #enter your App ID
facebook_locale: en_US
facebook_page:                                  #the URL of your Facebook Page
facebook_image: images/boonil.png                      #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
twitter_user:
twitter_card: true
twitter_image: images/boonil.png                       #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
